server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employees?serverTimezone=Asia/Seoul
    username: sbyoon
    password: 1234
  output:
    ansi:
      enabled: always

jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  show-sql: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

